# Generated by Django 4.0.4 on 2022-05-27 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=200)),
                ('preco_produto', models.CharField(max_length=20)),
                ('descricao_produto', models.CharField(max_length=200)),
                ('tamanho_produto', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=1)),
                ('categoria_produto', models.CharField(max_length=100)),
                ('img_produto', models.ImageField(blank=True, upload_to='fotos\\%d\\%m\\%Y')),
                ('data_produto', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status_produto', models.BooleanField(default=False, verbose_name='publicado')),
            ],
        ),
    ]
