# Generated by Django 4.0.4 on 2022-06-03 18:39

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roupas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='nome_produto', unique=True),
        ),
    ]
