# Generated by Django 4.0.4 on 2022-05-27 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roupas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntoRoupas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_conjunto', models.CharField(max_length=200)),
                ('preco_conjunto', models.CharField(max_length=20)),
                ('descricao_conjunto', models.CharField(max_length=200)),
                ('categoria_produto', models.CharField(max_length=100)),
                ('img_conjunto', models.ImageField(blank=True, upload_to='fotos\\%d\\%m\\%Y')),
                ('data_conjunto', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status_conjunto', models.BooleanField(default=False, verbose_name='publicado')),
                ('nome_produtos_do_conjunto', models.ManyToManyField(related_name='conjuntos', to='roupas.produto')),
            ],
        ),
    ]
