# Generated by Django 4.0.4 on 2022-05-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roupas', '0003_rename_categoria_produto_conjuntoroupas_categoria_conjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='marca_produto',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
