# Generated by Django 4.0.4 on 2022-05-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roupas', '0004_produto_marca_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjuntoroupas',
            name='numero_conjunto',
            field=models.CharField(choices=[('1', 'imagem 01'), ('2', 'imagem 02'), ('3', 'imagem 03'), ('4', 'imagem 04')], default=None, max_length=1),
        ),
    ]
